name: Update the OSS page
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Installs Poetry
        uses: Gr1N/setup-poetry@v8
      - name: Install the dependencies
        run: poetry install
      - name: Update the OSS page based on the latest README.md
        run: |
          wget -O PROFILE.md https://raw.githubusercontent.com/iosifache/iosifache/main/README.md
          python3 scripts/profile-readme-convert.py PROFILE.md content/oss.md
      - name: Compile the Pelican website
        run: poetry run pelican
      - name: Commit the changes
        run: |
          git add content/oss.md output/oss.html
          git config --global user.name "OSS page updater"
          git config --global user.email "username@users.noreply.github.com"
          git commit -a -m "Updates the OSS page"
          git push

